name: Grafana-Alloy-Image-Push

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

  push:
    branches:
      - main  # Runs only when pushing to main branch
  #     - '**'  # Runs on push to any branch

jobs:
  build:
    name: Dockerize and Push
    runs-on: ubuntu-latest

    permissions:
      # contents: read  # Allow read access to the repository contents
      packages: write  # Allow write access to packages (for pushing Docker images)
      # id-token: write  # Allow writing ID tokens for authentication

    defaults:
      run:
        working-directory: grafanaCloud

    # strategy:
    #   matrix:
    #     config:
    #       - cfg
    #       - abc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use latest version
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0  # needed for versioning/tag lookup

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # cp ${{ matrix.config }} config.alloy
      - name: Dockerize
        run: |
          docker buildx build --push -t ghcr.io/${{ github.repository_owner }}/myalloy:latest .

      - name: Run Container for Verification
        run: |
          docker run -d --rm --name test -p 12345:12345 ghcr.io/${{ github.repository_owner }}/myalloy:latest
          sleep 10  # Give it time to start
          docker logs test