name: Load test

on:
  push:
    paths:
      - '.github/workflows/load-test.yml'  # Trigger on changes to this workflow file
  #     - 'dotnet.FakeStoreIngestor/**'  # Trigger on changes in the dotnet.FakeStoreIngestor directory
  #     - '.github/workflows/fake-store-ingestor-dockerize.yml'  # Trigger on changes to this workflow file
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: fakestore
          MYSQL_USER: appuser
          MYSQL_PASSWORD: apppass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -prootpass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=20

      # fakestore-mock:
      #   image: ghcr.io/${{ github.repository_owner }}/fakestore-mock:latest
      #   ports:
      #     - 3000:3000
      #   options: >-
      #     --health-cmd="wget -qO- http://localhost:3000/products > /dev/null || exit 1"
      #     --health-interval=5s
      #     --health-timeout=3s
      #     --health-retries=20
      #     --health-start-period=10s

      # fakestore-api:
      #   image: ghcr.io/${{ github.repository_owner }}/fakestore-api:latest
      #   credentials:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #   env:
      #     ASPNETCORE_URLS: http://0.0.0.0:5171
      #     # ConnectionStrings__Default: Server=127.0.0.1;Port=3306;Database=fakestore;User=appuser;Password=apppass;TreatTinyAsBoolean=false;DefaultCommandTimeout=30
      #     ConnectionStrings__Default: Server=mysql;Port=3306;Database=fakestore;User=appuser;Password=apppass;TreatTinyAsBoolean=false;DefaultCommandTimeout=30
      #     Ingest__BaseUrl: "http://fakestore-mock:3000/"
      #     Ingest__ProductsEndpoint: "products"
      #   ports:
      #     - 5171:5171
      #   options: >-
      #     --health-cmd="curl -f http://localhost:5171/health || exit 1"
      #     --health-interval=10s
      #     --health-timeout=5s
      #     --health-retries=20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for MySQL
        run: |
          for i in {1..40}; do
            if mysqladmin ping -h127.0.0.1 -P3306 -uappuser -papppass --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
            if [ $i -eq 40 ]; then
              echo "MySQL failed to start"
              exit 1
            fi
          done

      - name: Wait for Mock Service
        run: |
          set -e
          docker rm -f fakestore-mock >/dev/null 2>&1 || true
          docker run -d --name fakestore-mock \
            --network host \
            -p 3000:3000 \
            ghcr.io/${{ github.repository_owner }}/fakestore-mock:latest

          for i in {1..40}; do
            if curl -sf http://localhost:3000/products >/dev/null; then
              echo "Mock service is up!"
              break
            fi
            echo "Waiting for mock service..."
            sleep 2
            if [ $i -eq 40 ]; then
              echo "fakestore-mock failed to start; printing container logs"
              docker logs fakestore-mock || true
              exit 1
            fi
          done

      # Run API container on host network so it can reach mysql+mock via localhost
      - name: Wait for API
        env:
          ASPNETCORE_URLS: http://0.0.0.0:5171
          ConnectionStrings__Default: Server=127.0.0.1;Port=3306;Database=fakestore;User=appuser;Password=apppass;TreatTinyAsBoolean=false;DefaultCommandTimeout=30
          Ingest__BaseUrl: http://localhost:3000/
          Ingest__ProductsEndpoint: products
        run: |
          set -e
          docker rm -f fakestore-api >/dev/null 2>&1 || true
          docker run -d --name fakestore-api \
            --network host \
            -p 5171:5171 \
            -e ASPNETCORE_URLS="$ASPNETCORE_URLS" \
            -e ConnectionStrings__Default="$ConnectionStrings__Default" \
            -e Ingest__BaseUrl="$Ingest__BaseUrl" \
            -e Ingest__ProductsEndpoint="$Ingest__ProductsEndpoint" \
            ghcr.io/${{ github.repository_owner }}/fakestore-api:latest

          # Wait for API health
          for i in {1..40}; do
            if curl -sf http://localhost:5171/health > /dev/null; then
              echo "API is up!"
              break
            fi
            echo "Waiting for API..."
            sleep 2
            if [ $i -eq 40 ]; then
              echo "API failed to start; printing container logs"
              docker logs fakestore-api || true
              exit 1
            fi
          done

      - name: Start Monitoring Grafana Alloy Agent
        env:
          # Secrets from GitHub → Settings → Secrets and variables → Actions
          GRAFANA_OTLP_ENDPOINT: ${{ secrets.GRAFANA_OTLP_ENDPOINT }}
          GRAFANA_OTLP_USERNAME: ${{ secrets.GRAFANA_OTLP_USERNAME }}
          GRAFANA_OTLP_PASSWORD: ${{ secrets.GRAFANA_OTLP_PASSWORD }}
          GRAFANA_RW_URL:        ${{ secrets.GRAFANA_RW_URL }}
          GRAFANA_RW_USERNAME:   ${{ secrets.GRAFANA_RW_USERNAME }}
          GRAFANA_RW_PASSWORD:   ${{ secrets.GRAFANA_RW_PASSWORD }}
        run: |
          set -e
          docker rm -f alloy-agent >/dev/null 2>&1 || true
          docker run -d --name alloy-agent \
            --network host \
            -p 12345:12345 \
            -e GRAFANA_OTLP_ENDPOINT="$GRAFANA_OTLP_ENDPOINT" \
            -e GRAFANA_OTLP_USERNAME="$GRAFANA_OTLP_USERNAME" \
            -e GRAFANA_OTLP_PASSWORD="$GRAFANA_OTLP_PASSWORD" \
            -e GRAFANA_RW_URL="$GRAFANA_RW_URL" \
            -e GRAFANA_RW_USERNAME="$GRAFANA_RW_USERNAME" \
            -e GRAFANA_RW_PASSWORD="$GRAFANA_RW_PASSWORD" \
            ghcr.io/${{ github.repository_owner }}/myalloy:latest

          # Wait for Alloy Agent health
          for i in {1..40}; do
            if curl -sf http://localhost:12345/health > /dev/null; then
              echo "Alloy Agent is up!"
              break
            fi
            echo "Waiting for Alloy Agent..."
            sleep 2
            if [ $i -eq 40 ]; then
              echo "Alloy Agent failed to start; printing container logs"
              docker logs alloy-agent || true
              exit 1
            fi
          done

      - name: Test - Import first 5
        run: |
          curl -sS -X POST 'http://localhost:5171/import/5' -H 'accept: */*'

      - name: Test - Read one
        run: |
          curl -sS 'http://localhost:5171/products/1' | jq . || true

      - name: Test - List all
        run: |
          curl -sS 'http://localhost:5171/products' | jq '.[0:5]' || true

      - name: Quick load test (Read one)
        run: |
          for i in {1..50}; do
            echo "Request #$i"
            curl -sS 'http://localhost:5171/products/1' | jq . || true
            sleep 0.2  # 200ms delay between requests, adjust as needed
          done

      # - name: Stop containers & processes
      #   if: always()
      #   run: |
      #     kill $(cat mock.pid) || true
